defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

title: Tyler Kindy
tagline: My personal site

permalink: /:categories/:year/:month/:day/:title

include:
  - _redirects
